document.writeln("<header>");
document.writeln("    <div class=\'page\' id=\'page1\'>");
document.writeln("        <div class=\'header-box\'>");
document.writeln("            <div class=\'header-top\'>");
document.writeln("                <div class=\'header-content container\'>");
document.writeln("                    <span class=\'welcome-text\'>欢迎来到吕梁师专计算机系官网</span>");
document.writeln("                    <span class=\'time-text\' id=\'current-time\'>当前时间为:</span>");
document.writeln("                    <div class=\'header-content-right\'>");
document.writeln("                        <ul>");
document.writeln("                            <li class=\'link1\'><a href=\'http://llsz.edu.cn/\' target=\'_blank\'>学校官网</a></li>");
document.writeln("                            <li class=\'link2\' onclick=\'Tip()\'><a>图书馆</a></li>");
document.writeln("                            <li class=\'link3\'><a href=\'http://llsz.edu.cn:8896/\' target=\'_blank\'>师生系统</a></li>");
document.writeln("                            <li class=\'link4\'><a href=\'http://llsz.edu.cn:8772/\' target=\'_blank\'>旧版网站</a></li>");
document.writeln("                            <li class=\'link5\'><span>|</span></li>");
document.writeln("                            <li class=\'link6\'><a>English</a></li>");
document.writeln("                            <li class=\'link7\'>");
document.writeln("                                <div class=\'search-icon\'>🔍</div>");
document.writeln("                                <input class=\'search-box\' placeholder=\'这是里吕专百家通\' type=\'text\'/>");
document.writeln("                            </li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("");
document.writeln("            <div class=\'header-bottom container\'>");
document.writeln("                <div class=\'logo\'></div>");
document.writeln("                <nav class=\'nav\'>");
document.writeln("                    <ul>");
document.writeln("                        <li><a class=\'mean\' href=\'../../index.html\'><em class=\'home\'>首页</em></a></li>");
document.writeln("                        <li>");
document.writeln("                            <a class=\'mean\'><em>系部概况</em></a>");
document.writeln("                            <div class=\'dropdown\'>");
document.writeln("                                <ul>");
document.writeln("                                    <li><a href=\'../../ejym/xbgk/xbjj.html\'>系部简介</a></li>");
document.writeln("                                    <li><a href=\'../../ejym/xbgk/bxzz.html\'>办学宗旨</a></li>");
document.writeln("                                    <li><a href=\'../../ejym/xbgk/fzlc.html\'>发展历程</a></li>");
document.writeln("                                    <li><a href=\'../../ejym/xbgk/rycj.html\'>荣誉成就</a></li>");
document.writeln("                                </ul>");
document.writeln("                            </div>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a class=\'mean\'><em>党建工作</em></a>");
document.writeln("                            <div class=\'dropdown\'>");
document.writeln("                                <ul>");
document.writeln("                                    <li><a href=\'../../ejym/djgz/dzbjj.html\'>党支部简介</a></li>");
document.writeln("                                    <li><a href=\'../../ejym/djgz/zzhd.html\'>组织活动</a></li>");
document.writeln("                                    <li><a href=\'../../ejym/djgz/dzbjj.html\'>党员风采</a></li>");
document.writeln("                                    <li><a href=\'../../ejym/djgz/dzbjj.html\'>学习园地</a></li>");
document.writeln("                                </ul>");
document.writeln("                            </div>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a class=\'mean\'><em>专业方向</em></a>");
document.writeln("                            <div class=\'dropdown\'>");
document.writeln("                                <ul>");
document.writeln("                                    <li><a href=\'../../ejym/zyfx/jsjyyjs.html\'>计算机应用技术</a></li>");
document.writeln("                                    <li><a href=\'../../ejym/zyfx/rgznyyy.html\'>人工智能与应用</a></li>");
document.writeln("                                    <li><a href=\'../../ejym/zyfx/znhlwljs.html\'>智能互联网络技术</a></li>");
document.writeln("                                    <li><a href=\'../../ejym/zyfx/sjzxyxygl.html\'>数据中心运行与管理</a></li>");
document.writeln("                                </ul>");
document.writeln("                            </div>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a class=\'mean\'><em>教学科研</em></a>");
document.writeln("                            <div class=\'dropdown\'>");
document.writeln("                                <ul>");
document.writeln("                                    <li><a href=\'../../ejym/jxky/kyxm.html\'>科研项目</a></li>");
document.writeln("                                    <li><a href=\'../../ejym/jxky/xsjz.html\'>学术讲座</a></li>");
document.writeln("                                    <li><a href=\'../../ejym/jxky/jsjs.html\'>技术竞赛</a></li>");
document.writeln("                                </ul>");
document.writeln("                            </div>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a class=\'mean\'><em>实训基地</em></a>");
document.writeln("                            <div class=\'dropdown\'>");
document.writeln("                                <ul>");
document.writeln("                                    <li><a href=\'../../ejym/sxjd/sxsjs.html\'>实训室介绍</a></li>");
document.writeln("                                    <li><a href=\'../../ejym/sxjd/xqhz.html\'>校企合作</a></li>");
document.writeln("                                    <li><a href=\'../../ejym/sxjd/sxsb.html\'>实训设备</a></li>");
document.writeln("                                    <li><a href=\'../../ejym/sxjd/rycj.html\'>荣誉成就</a></li>");
document.writeln("                                </ul>");
document.writeln("                            </div>");
document.writeln("                        </li>");
document.writeln("                        <li>");
document.writeln("                            <a class=\'mean\'><em>校友之家</em></a>");
document.writeln("                            <div class=\'dropdown\'>");
document.writeln("                                <ul>");
document.writeln("                                    <li><a href=\'../../ejym/xyzj/xyfc.html\'>校友风采</a></li>");
document.writeln("                                    <li><a href=\'../../ejym/xyzj/xyhd.html\'>校友活动</a></li>");
document.writeln("                                    <li><a href=\'../../ejym/xyzj/yxbys.html\'>优秀毕业生</a></li>");
document.writeln("                                </ul>");
document.writeln("                            </div>");
document.writeln("                        </li>");
document.writeln("                        <li><a class=\'mean\' href=\'../../ejym/xzzq/xzzq.html\'><em chass=\'download\'>下载专区</em></a></li>");
document.writeln("                    </ul>");
document.writeln("                </nav>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("</header>");
document.writeln("</header>");
document.writeln("</header>");
document.writeln("    <div class=\'bg\'>");
document.writeln("        ");
document.writeln("    </div>");