document.writeln("    <footer class=\'footer-section\'>");
document.writeln("        <div class=\'page\' id=\'page5\'>");
document.writeln("            <div class=\'container\'>");
document.writeln("                <div class=\'footer-content\'>");
document.writeln("                    <div class=\'footer-col\'>");
document.writeln("                        <div class=\'contact-info\'>");
document.writeln("                            <h3>联系我们</h3>");
document.writeln("                            <p>");
document.writeln("                                <img alt=\'校址\' height=\'18px\' src=\'./images/address.svg\' width=\'18px\'>");
document.writeln("                                山西省吕梁市方山县大武镇保安村");
document.writeln("                            </p>");
document.writeln("                            <p>");
document.writeln("                                <img alt=\'电话\' height=\'18px\' src=\'./images/phone.svg\' width=\'18px\'>");
document.writeln("                                <a href=\'tel:0358-2286036\'>0358-2286036</a> /");
document.writeln("                                <a href=\'tel:0358-2286039\'>2286039</a>");
document.writeln("                            </p>");
document.writeln("                            <p>");
document.writeln("                                <img alt=\'邮箱\' height=\'18px\' src=\'./images/email.svg\' width=\'18px\'>");
document.writeln("                                <a href=\'mailto:xxxxx@llsz.edu.cn\'>xxxxx@llsz.edu.cn</a>");
document.writeln("                            </p>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("    ");
document.writeln("                    <div class=\'footer-col\'>");
document.writeln("                        <h3>快速导航</h3>");
document.writeln("                        <ul class=\'footer-links\'>");
document.writeln("                            <li><a href=\'javascript:void(0)\' onclick=\'Tip()\'>系部概况</a></li>");
document.writeln("                            <li><a href=\'javascript:void(0)\' onclick=\'Tip()\'>专业方向</a></li>");
document.writeln("                            <li><a href=\'javascript:void(0)\' onclick=\'Tip()\'>教学科研</a></li>");
document.writeln("                            <li><a href=\'http://llsz.edu.cn:8896\' target=\'_blank\'>教务系统</a></li>");
document.writeln("                            <li><a href=\'http://llsz.edu.cn/\' target=\'_blank\'>校园门户</a></li>");
document.writeln("                        </ul>");
document.writeln("                    </div>");
document.writeln("    ");
document.writeln("                    <div class=\'footer-col\'>");
document.writeln("                        <h3>关注我们</h3>");
document.writeln("                        <div class=\'qr-codes\'>");
document.writeln("                            <div class=\'qr-code\'>");
document.writeln("                                <img alt=\'微信公众号\' height=\'120\' src=\'images/QR.jpg\'>");
document.writeln("                                <p>微信公众号</p>");
document.writeln("                            </div>");
document.writeln("                        </div>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("    ");
document.writeln("                <div class=\'footer-bottom\'>");
document.writeln("                    <div class=\'copyright\'>");
document.writeln("                        <p>Copyright © 2024 吕梁师范高等专科学校计算机系 版权所有</p>");
document.writeln("                        <p>ICP备案号：晋ICP备?????????????????号-1</p>");
document.writeln("                    </div>");
document.writeln("                    <div class=\'back-to-top\'>");
document.writeln("                        <i class=\'fas fa-arrow-up\'></i>");
document.writeln("                    </div>");
document.writeln("                </div>");
document.writeln("            </div>");
document.writeln("        </div>");
document.writeln("    </footer>");